    {!! \Illuminate\Support\Str::markdown("# Terms of Purchase
By submitting your registration, and purchasing the ticket(s), you agree to be bound by this Terms of Purchase (the “Terms”) as outlined by Gainful, LLC, d.b.a., Kabuvu ('Kabuvu') for Catch Your Vision (the “Event”).

## Cancellation and Refund
Refunds are not provided for ticket(s) purchased, you may however transfer or assign your ticket(s) to someone else, provided that such transfers shall be completed no later than one (1) hour before the event you registered for. Refunds shall not be provided for no-shows. Kabuvu reserves the right to cancel or change the date(s) of the Event, vary the content, schedule or venue at any time and for any reason. In the event that the date(s) of the Event are changed to new date(s) that is within twelve (12) months of the originally scheduled opening date of the Event, or where the Event is canceled but is reasonably expected by Kabuvu to be held at any time in the next calendar year, then, unless otherwise stated, your registration will be deemed to be valid for the Event on the new date(s) or when it is next staged (as applicable) in the same way that it would have applied to the originally scheduled Event (and no refund of any paid registration fees will be issued). Kabuvu accepts no liability for any such variation or cancellation. Where all or part of the Event is canceled and is not reasonably expected by Kabuvu to be held in the next calendar year, then your registration will no longer be deemed to be valid for the Event (or the canceled portion of the Event, as applicable) and, at your election, any paid registration/ticket(s) fees for the Event (or the canceled portion of the Event, as applicable) will be refunded or a credit note issued for the same, and you will be released from paying any further amount of registration/ticket(s) fees for the Event (or the canceled portion of the Event, as applicable). Service charges are non-refundable. Personal arrangements, including, without limitation, travel and accommodation, are at your own risk and Kabuvu will not be liable for any costs relating to such arrangements. You acknowledge and agree that the provisions of this paragraph set out your sole remedy in the event of cancellation or the changing of the date(s) of the Event and all other liability of Kabuvu is hereby expressly excluded.

## Code of Conduct
The Event is dedicated to providing a fun, engaging, and safe event for everyone. All Event participants, including attendees, speakers, sponsors, vendors, and Kabuvu staS (“Participants”) must comply with the Kabuvu Code of Conduct (the “Code of Conduct”). The Code of Conduct expectations for participant behavior and sets expectations for attendees and participants' behavior. By attending the Event, you agree to abide by this Code of Conduct. Anyone found to be violating this Code of Conduct may be expelled at the discretion of Kabuvu.

## Personal Data
You understand and consent that as part of your registration and attendance at the Event, personal data will be collected by Kabuvu and Participants for the purposes of (but not limited to) tracking attendance via email. By registering, or accepting an invitation to attend the Event, you hereby agree to be bound by Kabuvu's Privacy Policy and you consent to the sharing of your personal data by Kabuvu for the purposes outlined in these Terms. Kabuvu will at all times comply with the Data Protection Act 1998 and will hold your personal data and use the same solely for the purposes stated in this Terms or informing you about future events or services that may be of interest to you. Kabuvu will not share your personal data with any third party (other than is necessary for it to carry out its obligations under these Terms) without your express permission. If you do not wish to have your personal data shared, kindly contact the Event Team.

## Force Majeure
Kabuvu shall not be liable for any delay or failure to perform any of its obligations, including canceling or rescheduling the Event, if the delay or failure results from circumstances outside its control, including but not limited to: acts of God, flood, drought, earthquake or other natural disaster; strikes or labor disputes, civil unrest or riots, war, threat of war or other armed conflict, infectious diseases, epidemic or pandemic, any law or action taken by a government or public authority (“Force Majeure”). Kabuvu will notify you as soon as reasonably possible in the event of a Force Majeure. In the event of rescheduling or cancellation as a result of Force Majeure, no refunds will be issued, however, Kabuvu may at its sole discretion exchange the tickets for entry to another event.
") !!}
